server:
  port: 8081

springfox:
  documentation:
    auto-startup: false

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_ADDR:localhost:9092}

disqualified-officers:
  delta:
    group-id: disqualified-officers-delta-consumer
    main-id: disqualified-officers-main-consumer
    retry-id: disqualified-officers-retry-consumer
    retry-attempts: 4
    backoff-delay: 100
    topic: disqualified-officers-delta

logger:
  namespace: disqualified-officers-delta-consumer

api:
  disqualified-officers-data-api-key: ${DISQUALIFIED_OFFICERS_DATA_API_KEY:localhost}
  api-url: ${API_URL:http://localhost:8888}
  internal-api-url: ${INTERNAL_API_URL:localhost}

wiremock:
  server:
    port: 8888

