spring:
  kafka:
    bootstrap-servers: localhost:9092

logger:
  namespace: disqualified-officers-delta-consumer

insolvency:
  delta:
    group-id: disqualified-officers-delta-consumer
    topic: disqualified-officers-delta
    retry-attempts: 1
    backoff-delay: 100